# EnchantmentLimit 配置文件

# 消息设置
messages:
  pluginEnabled: "附魔限制插件已启用！"
  pluginDisabled: "附魔限制插件已禁用！"
  replaceSuccess: "&a成功替换自动祛魔台逻辑！"
  replaceFail: "&c替换自动祛魔台逻辑失败！"
  noPermission: "&c你没有权限执行此命令！"
  configReloaded: "&a配置文件已重载！"

# 功能设置
settings:
  enableMessages: true
  # 祛魔机处理模式
  # strict: 严格模式 - 放入超过限制的附魔物品时失效，有点硬核因为直接没反应不推荐
  # convert: 转换模式 - 允许放入，但会将超过限制的附魔等级降低到允许的最高等级
  mode: "convert"

# 附魔限制
# 格式: enchantments.minecraft:附魔ID: 最大等级
enchantments:
  minecraft:sharpness: 5
  minecraft:efficiency: 5
  minecraft:fortune: 3
  minecraft:looting: 3
  minecraft:power: 5
  minecraft:protection: 4
  minecraft:fire_protection: 4
  minecraft:blast_protection: 4
  minecraft:projectile_protection: 4
  minecraft:feather_falling: 4
  minecraft:thorns: 3
  minecraft:depth_strider: 3
  minecraft:frost_walker: 2
  minecraft:soul_speed: 3
  minecraft:swift_sneak: 3
  minecraft:knockback: 2
  minecraft:fire_aspect: 2
  minecraft:unbreaking: 3
  minecraft:silk_touch: 1
  minecraft:aqua_affinity: 1
  minecraft:respiration: 3
  minecraft:infinity: 1
  minecraft:flame: 1
  minecraft:punch: 2
  minecraft:loyalty: 3
  minecraft:impaling: 5
  minecraft:riptide: 3
  minecraft:channeling: 1
  minecraft:multishot: 1
  minecraft:quick_charge: 3
  minecraft:piercing: 4
  minecraft:mending: 1
  minecraft:binding_curse: 1
  minecraft:vanishing_curse: 1
  minecraft:sweeping: 3

